NumPy, which stands for Numerical Python, is a powerful library in Python used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy forms the foundation for many other libraries in the scientific computing ecosystem of Python.

Key features of NumPy include:

1. **Efficient Array Operations:** NumPy arrays are faster and more memory-efficient than Python lists for numerical operations, especially for large datasets. This efficiency is achieved through optimized, compiled C code.

2. **Multi-dimensional Arrays:** NumPy supports arrays of any dimensionality, including 1-D arrays (vectors), 2-D arrays (matrices), and higher-dimensional arrays.

3. **Broadcasting:** NumPy allows operations on arrays of different shapes and sizes through broadcasting, which automatically aligns arrays to perform element-wise operations.

4. **Linear Algebra:** NumPy provides a rich set of functions for linear algebra operations, such as matrix multiplication, eigenvalues, and decomposition.

5. **Random Number Generation:** NumPy includes functions for generating random numbers and random sampling from various probability distributions.

6. **Integration with Other Libraries:** Many scientific and data analysis libraries in Python, such as SciPy, Pandas, and Matplotlib, are built on top of NumPy, making it an essential component of the Python data science ecosystem.

Overall, NumPy is widely used in various domains, including data analysis, machine learning, signal processing, image processing, and computational science, due to its efficiency, flexibility, and extensive functionality for numerical computing tasks.

An array is a data structure that stores a collection of elements, typically of the same data type, arranged in contiguous memory locations. Arrays provide a way to efficiently manage and manipulate large sets of data in programming languages.

Key characteristics of arrays include:

1. **Homogeneity:** Arrays contain elements of the same data type, ensuring uniformity and efficient memory usage.

2. **Contiguous Memory:** Array elements are stored in adjacent memory locations, allowing for fast access and traversal.

3. **Fixed Size:** Arrays have a fixed size determined at the time of creation, which cannot be changed dynamically.

4. **Indexing:** Elements in an array are accessed using an index, which represents their position within the array. Array indices typically start from 0.

Arrays are widely used in various programming scenarios, including numerical computations, data manipulation, and algorithm implementation. They form the foundation of many higher-level data structures and are essential for efficient data storage and processing in computer science and software development.

In [2]:
import numpy as np

In [4]:
# 1. Creating NumPy Arrays
heights_cm = np.array([165, 170, 155, 180, 172])
print("1. Creating NumPy Arrays:")
print("Heights:", heights_cm)

1. Creating NumPy Arrays:
Heights: [165 170 155 180 172]


In [5]:
# 2. Array Operations
average_height = np.mean(heights_cm)
max_height = np.max(heights_cm)
print("2. Array Operations:")
print("Average height:", average_height)
print("Maximum height:", max_height)

2. Array Operations:
Average height: 168.4
Maximum height: 180


In [6]:
# 3. Multi-dimensional Arrays
temperature_data = np.array([[25, 28, 30], [22, 23, 24], [30, 32, 28]])
print("3. Multi-dimensional Arrays:")
print("Temperature data:")
print(temperature_data)

3. Multi-dimensional Arrays:
Temperature data:
[[25 28 30]
 [22 23 24]
 [30 32 28]]


In [7]:
# 4. Array Indexing and Slicing
first_city_temperatures = temperature_data[0]
second_day_temperatures = temperature_data[:, 1]
print("4. Array Indexing and Slicing:")
print("Temperatures for the first city:", first_city_temperatures)
print("Temperatures for the second day:", second_day_temperatures)

4. Array Indexing and Slicing:
Temperatures for the first city: [25 28 30]
Temperatures for the second day: [28 23 32]


In [8]:
# 5. Array Broadcasting
temperatures_fahrenheit = (temperature_data * 9/5) + 32
print("5. Array Broadcasting:")
print("Temperatures in Fahrenheit:")
print(temperatures_fahrenheit)

5. Array Broadcasting:
Temperatures in Fahrenheit:
[[77.  82.4 86. ]
 [71.6 73.4 75.2]
 [86.  89.6 82.4]]


In [9]:
# 6. Linear Algebra Operations
sales = np.array([[100, 200, 150], [300, 250, 180]])
prices = np.array([[10, 15, 20], [8, 12, 18]])
revenue = np.dot(sales, prices.T)
print("6. Linear Algebra Operations:")
print("Revenue from sales (in dollars):")
print(revenue)

6. Linear Algebra Operations:
Revenue from sales (in dollars):
[[ 7000  5900]
 [10350  8640]]


In [10]:
# 7. Random Number Generation
dice_rolls = np.random.randint(1, 7, size=(2, 3))
print("7. Random Number Generation:")
print("Dice rolls:")
print(dice_rolls)

7. Random Number Generation:
Dice rolls:
[[2 5 5]
 [3 4 6]]


Here are short notes about the methods used in the examples provided:

1. **Creating NumPy Arrays:**
   - `np.array()`: Converts a Python list to a NumPy array.

2. **Array Operations:**
   - `np.mean()`: Computes the average of elements in a NumPy array.
   - `np.max()`: Finds the maximum value in a NumPy array.

3. **Multi-dimensional Arrays:**
   - `np.array()`: Creates a multi-dimensional NumPy array from a list of lists.

4. **Array Indexing and Slicing:**
   - Indexing with `[ ]`: Accesses elements or slices of a NumPy array.

5. **Array Broadcasting:**
   - Element-wise arithmetic operations are performed on NumPy arrays due to broadcasting.

6. **Linear Algebra Operations:**
   - `np.dot()`: Computes the dot product of two arrays (matrix multiplication).
   - `.T`: Transposes a NumPy array (rows become columns and vice versa).

7. **Random Number Generation:**
   - `np.random.randint()`: Generates random integers within a specified range.

8. **Data Analysis with NumPy:**
   - Placeholder for loading and analyzing stock price data from a CSV file. Actual methods would include functions like `np.loadtxt()` for loading data and `np.diff()` for computing differences between consecutive elements.

These methods are fundamental to using NumPy arrays effectively and cover basic operations, mathematical computations, data manipulation, and random number generation. Experimenting with these methods and exploring their variations will deepen your understanding of NumPy and its capabilities.

In [12]:
# Import NumPy library
import numpy as np

# Creating NumPy Arrays

## From a Python List
my_list = [1, 2, 3]
print("List:", my_list)


List: [1, 2, 3]


In [14]:
# Convert list to NumPy array
np_array_from_list = np.array(my_list)
print("NumPy array from list:", np_array_from_list)
print()

my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Matrix:", my_matrix)
print()

# Convert matrix to NumPy array
np_array_from_matrix = np.array(my_matrix)
print("NumPy array from matrix:")
print(np_array_from_matrix)

NumPy array from list: [1 2 3]

Matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

NumPy array from matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
## Built-in Methods

### arange
print("np.arange(0, 10):", np.arange(0, 10))
print("np.arange(0, 11, 2):", np.arange(0, 11, 2))
print()

### zeros and ones
print("np.zeros(3):", np.zeros(3))
print("np.zeros((5, 5)):")
print(np.zeros((5, 5)))
print()

print("np.ones(3):", np.ones(3))
print("np.ones((3, 3)):")
print(np.ones((3, 3)))
print()

### linspace
print("np.linspace(0, 10, 3):", np.linspace(0, 10, 3))
print("np.linspace(0, 10, 50):", np.linspace(0, 10, 50))
print()

## eye
print("np.eye(4):")
print(np.eye(4))
print()

## Random 

### rand
print("np.random.rand(2):", np.random.rand(2))
print("np.random.rand(5, 5):")
print(np.random.rand(5, 5))
print()

### randn
print("np.random.randn(2):", np.random.randn(2))
print("np.random.randn(5, 5):")
print(np.random.randn(5, 5))
print()

### randint
print("np.random.randint(1, 100):", np.random.randint(1, 100))
print("np.random.randint(1, 100, 10):", np.random.randint(1, 100, 10))

np.arange(0, 10): [0 1 2 3 4 5 6 7 8 9]
np.arange(0, 11, 2): [ 0  2  4  6  8 10]

np.zeros(3): [0. 0. 0.]
np.zeros((5, 5)):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(3): [1. 1. 1.]
np.ones((3, 3)):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

np.linspace(0, 10, 3): [ 0.  5. 10.]
np.linspace(0, 10, 50): [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

np.eye(4):
[[1. 0. 0. 0.]
 [0. 1. 

In [16]:
# Array Attributes and Methods

## Reshape
arr = np.arange(25)
print("arr:", arr)
print("arr.reshape(5, 5):")
print(arr.reshape(5, 5))
print()

### max, min, argmax, argmin
ranarr = np.random.randint(0, 50, 10)
print("ranarr:", ranarr)
print("ranarr.max():", ranarr.max())
print("ranarr.argmax():", ranarr.argmax())
print("ranarr.min():", ranarr.min())
print("ranarr.argmin():", ranarr.argmin())
print()

## Shape
# Vector
print("arr.shape:", arr.shape)
print("arr.reshape(1, 25):", arr.reshape(1, 25))
print("arr.reshape(1, 25).shape:", arr.reshape(1, 25).shape)
print("arr.reshape(25, 1):", arr.reshape(25, 1))
print("arr.reshape(25, 1).shape:", arr.reshape(25, 1).shape)
print()

## dtype
print("arr.dtype:", arr.dtype)

# Congratulations! You've learned about NumPy arrays.

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
arr.reshape(5, 5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

ranarr: [ 2 27 26 40 11 33 41  6 11 19]
ranarr.max(): 41
ranarr.argmax(): 6
ranarr.min(): 2
ranarr.argmin(): 0

arr.shape: (25,)
arr.reshape(1, 25): [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
arr.reshape(1, 25).shape: (1, 25)
arr.reshape(25, 1): [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
arr.reshape(25, 1).shape: (25, 1)

arr.dtype: int64
